[package]
name = "munapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
serde = {version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
